version: '3.8'

services:
  libre-book:
    build: .
    container_name: libre-book
    environment:
      - RUST_LOG=${RUST_LOG}
      - RUST_BACKTRACE=${RUST_BACKTRACE}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8080:8080"
